/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.sprint1;

import java.util.Random;

/**
 *
 * @author Lourdes
 */
public class GerenciadorSO extends javax.swing.JFrame {
        Random random = new Random();
    /**
     * Creates new form GerenciadorSO
     */
    
    

    public GerenciadorSO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpGuias = new javax.swing.JTabbedPane();
        PnlDesempenho = new javax.swing.JPanel();
        lblCPU = new javax.swing.JLabel();
        lblCPUUtilizaçao = new javax.swing.JLabel();
        lblCPUVelAtual = new javax.swing.JLabel();
        lblCPUVelMax = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCPUPorcentagem = new javax.swing.JLabel();
        lblCPUValorVelocAtual = new javax.swing.JLabel();
        lblCPUValorVelMax = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        lblMemRAM = new javax.swing.JLabel();
        lblMemUso = new javax.swing.JLabel();
        lblMemUtilizacao = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMemPorcentagem = new javax.swing.JLabel();
        lblMemValorUso = new javax.swing.JLabel();
        lblMemValorRAM = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblDiscoUtilizacao = new javax.swing.JLabel();
        lblDiscoUsado = new javax.swing.JLabel();
        lblDiscoLivre = new javax.swing.JLabel();
        lblDiscoCapacidade = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblDiscoPorcentagem = new javax.swing.JLabel();
        lblDiscoValorUsado = new javax.swing.JLabel();
        DiscoValorLivre = new javax.swing.JLabel();
        lblDiscoValorCapacidade = new javax.swing.JLabel();
        pnlAplicativos1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnFinalizarTarefa = new javax.swing.JButton();
        btnAlternar = new javax.swing.JButton();
        btnNovaTarefa = new javax.swing.JButton();
        pnlProcessos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProcessos = new javax.swing.JTable();
        btnMostrarProcessos = new javax.swing.JButton();
        btnFinalizarProcesso = new javax.swing.JButton();
        pnlUsuarios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnArquivo = new javax.swing.JMenu();
        MnOpcoes = new javax.swing.JMenu();
        MnExibir = new javax.swing.JMenu();
        MnAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpGuias.setBackground(new java.awt.Color(255, 255, 255));

        PnlDesempenho.setBackground(new java.awt.Color(255, 255, 255));

        lblCPU.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCPU.setText("CPU");

        lblCPUUtilizaçao.setText("Utilização");

        lblCPUVelAtual.setText("Velocidade atual");

        lblCPUVelMax.setText("Velocidade maxima");

        lblCPUPorcentagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCPUPorcentagem.setText("%");

        lblCPUValorVelocAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCPUValorVelocAtual.setText("GHz");

        lblCPUValorVelMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCPUValorVelMax.setText("5 GHz");

        lblMemoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMemoria.setText("Memória");

        lblMemRAM.setText("Memória RAM");

        lblMemUso.setText("Em uso");

        lblMemUtilizacao.setText("Utilização");

        lblMemPorcentagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMemPorcentagem.setText("%");

        lblMemValorUso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMemValorUso.setText("GHz");

        lblMemValorRAM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMemValorRAM.setText("8 GB");

        lblDisco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDisco.setText("Disco");

        lblDiscoUtilizacao.setText("Utilização");

        lblDiscoUsado.setText("Espaço usado");

        lblDiscoLivre.setText("Espaço livre");

        lblDiscoCapacidade.setText("Capacidade");

        lblDiscoPorcentagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiscoPorcentagem.setText("%");

        lblDiscoValorUsado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiscoValorUsado.setText("Gb");

        DiscoValorLivre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DiscoValorLivre.setText("GHz");

        lblDiscoValorCapacidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiscoValorCapacidade.setText("500 GB");

        javax.swing.GroupLayout PnlDesempenhoLayout = new javax.swing.GroupLayout(PnlDesempenho);
        PnlDesempenho.setLayout(PnlDesempenhoLayout);
        PnlDesempenhoLayout.setHorizontalGroup(
            PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addComponent(lblCPU)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCPUUtilizaçao)
                        .addGap(63, 63, 63)
                        .addComponent(lblCPUVelAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCPUVelMax)
                        .addGap(20, 20, 20))))
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addComponent(lblMemoria)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblMemUtilizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMemUso)
                        .addGap(89, 89, 89)
                        .addComponent(lblMemRAM)
                        .addGap(27, 27, 27))))
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCPUPorcentagem)
                .addGap(90, 90, 90)
                .addComponent(lblCPUValorVelocAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCPUValorVelMax)
                .addGap(39, 39, 39))
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlDesempenhoLayout.createSequentialGroup()
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisco)
                            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblDiscoUtilizacao)
                                .addGap(33, 33, 33)
                                .addComponent(lblDiscoUsado)
                                .addGap(38, 38, 38)
                                .addComponent(lblDiscoLivre)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblMemPorcentagem)
                        .addGap(102, 102, 102)
                        .addComponent(lblMemValorUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMemValorRAM)))
                .addGap(37, 37, 37))
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(lblDiscoCapacidade)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblDiscoPorcentagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDiscoValorUsado)
                        .addGap(54, 54, 54)
                        .addComponent(DiscoValorLivre)
                        .addGap(59, 59, 59)
                        .addComponent(lblDiscoValorCapacidade)
                        .addGap(30, 30, 30))))
        );
        PnlDesempenhoLayout.setVerticalGroup(
            PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDesempenhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPUUtilizaçao)
                    .addComponent(lblCPUVelAtual)
                    .addComponent(lblCPUVelMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPUValorVelocAtual)
                    .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCPUPorcentagem)
                        .addComponent(lblCPUValorVelMax)))
                .addGap(18, 18, 18)
                .addComponent(lblMemoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemUtilizacao)
                    .addComponent(lblMemUso)
                    .addComponent(lblMemRAM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemValorRAM)
                    .addComponent(lblMemPorcentagem)
                    .addComponent(lblMemValorUso))
                .addGap(18, 18, 18)
                .addComponent(lblDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoCapacidade)
                    .addComponent(lblDiscoUtilizacao)
                    .addComponent(lblDiscoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscoUsado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoValorUsado)
                    .addComponent(DiscoValorLivre)
                    .addComponent(lblDiscoValorCapacidade)
                    .addComponent(lblDiscoPorcentagem))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        tbpGuias.addTab("Desempenho", PnlDesempenho);

        pnlAplicativos1.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Google Chrome", "Executando"},
                {"Apache NetBeans", "Executando"}
            },
            new String [] {
                "Tarefa", "Status"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        btnFinalizarTarefa.setText("Finalizar Tarefa");

        btnAlternar.setText("Alternar para");

        btnNovaTarefa.setText("Nova Tarefa");

        javax.swing.GroupLayout pnlAplicativos1Layout = new javax.swing.GroupLayout(pnlAplicativos1);
        pnlAplicativos1.setLayout(pnlAplicativos1Layout);
        pnlAplicativos1Layout.setHorizontalGroup(
            pnlAplicativos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAplicativos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAplicativos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlAplicativos1Layout.createSequentialGroup()
                        .addComponent(btnFinalizarTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlternar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnNovaTarefa)))
                .addContainerGap())
        );
        pnlAplicativos1Layout.setVerticalGroup(
            pnlAplicativos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAplicativos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAplicativos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovaTarefa)
                    .addComponent(btnAlternar)
                    .addComponent(btnFinalizarTarefa))
                .addGap(69, 69, 69))
        );

        tbpGuias.addTab("Aplicativos", pnlAplicativos1);

        pnlProcessos.setBackground(new java.awt.Color(255, 255, 255));

        tbProcessos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"netbeans.exe", "Aluno", "00", "1.504.452 K"},
                {"chrome.exe", "Aluno", "00", "2.543 K"},
                {"chrome.exe", "Aluno", "00", "2.765 K"},
                {"chrome.exe", "Aluno", "00", "3.043 K"}
            },
            new String [] {
                "Nome da Imagem", "Nome de Usuario", "CPU", "Memória"
            }
        ));
        tbProcessos.setGridColor(new java.awt.Color(255, 255, 255));
        tbProcessos.setShowGrid(true);
        jScrollPane3.setViewportView(tbProcessos);

        btnMostrarProcessos.setText("Mostrar processos de todos os usuários");

        btnFinalizarProcesso.setText("Finalizar processo");

        javax.swing.GroupLayout pnlProcessosLayout = new javax.swing.GroupLayout(pnlProcessos);
        pnlProcessos.setLayout(pnlProcessosLayout);
        pnlProcessosLayout.setHorizontalGroup(
            pnlProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlProcessosLayout.createSequentialGroup()
                        .addComponent(btnMostrarProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnFinalizarProcesso)))
                .addContainerGap())
        );
        pnlProcessosLayout.setVerticalGroup(
            pnlProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarProcesso)
                    .addComponent(btnMostrarProcessos))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        tbpGuias.addTab("Processos", pnlProcessos);

        pnlUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aluno", "1", "Ativo", "Console"}
            },
            new String [] {
                "Usuário", "Identificação", "Status", "Sessão"
            }
        ));
        tbUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tbUsuarios);

        jButton1.setText("Desconectar");

        jButton2.setText("Logoff");

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpGuias.addTab("Usuários", pnlUsuarios);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        MnArquivo.setText("Arquivo");
        jMenuBar1.add(MnArquivo);

        MnOpcoes.setText("Opções");
        jMenuBar1.add(MnOpcoes);

        MnExibir.setText("Exibir");
        jMenuBar1.add(MnExibir);

        MnAjuda.setText("Ajuda");
        jMenuBar1.add(MnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Double cpu,ram,velocidade,usoRam,disco,discoUso,discoLivre;
       
      
        cpu = random.nextDouble()* 100;
        velocidade = random.nextDouble()* 5;
        
        lblCPUPorcentagem.setText(String.format("%.1f", cpu)+ "%");    
        lblCPUValorVelocAtual.setText(String.format("%.1f", velocidade)+ " GHz"); 
        
        usoRam = random.nextDouble()* 8;
        ram = (usoRam*100)/8;
        
        lblMemPorcentagem.setText(String.format("%.1f", ram)+ "%");
        lblMemValorUso.setText(String.format("%.1f", usoRam)+ " GB"); 
        
        discoUso = random.nextDouble()*500;
        discoLivre = 500 - discoUso;
        disco = (discoUso*100)/500;
        
        lblDiscoValorUsado.setText(String.format("%.0f", discoUso)+ " GB"); 
        DiscoValorLivre.setText(String.format("%.0f", discoLivre)+ " GB"); 
        lblDiscoPorcentagem.setText(String.format("%.1f", disco)+ "%");
       
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiscoValorLivre;
    private javax.swing.JMenu MnAjuda;
    private javax.swing.JMenu MnArquivo;
    private javax.swing.JMenu MnExibir;
    private javax.swing.JMenu MnOpcoes;
    private javax.swing.JPanel PnlDesempenho;
    private javax.swing.JButton btnAlternar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnFinalizarProcesso;
    private javax.swing.JButton btnFinalizarTarefa;
    private javax.swing.JButton btnMostrarProcessos;
    private javax.swing.JButton btnNovaTarefa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblCPUPorcentagem;
    private javax.swing.JLabel lblCPUUtilizaçao;
    private javax.swing.JLabel lblCPUValorVelMax;
    private javax.swing.JLabel lblCPUValorVelocAtual;
    private javax.swing.JLabel lblCPUVelAtual;
    private javax.swing.JLabel lblCPUVelMax;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblDiscoCapacidade;
    private javax.swing.JLabel lblDiscoLivre;
    private javax.swing.JLabel lblDiscoPorcentagem;
    private javax.swing.JLabel lblDiscoUsado;
    private javax.swing.JLabel lblDiscoUtilizacao;
    private javax.swing.JLabel lblDiscoValorCapacidade;
    private javax.swing.JLabel lblDiscoValorUsado;
    private javax.swing.JLabel lblMemPorcentagem;
    private javax.swing.JLabel lblMemRAM;
    private javax.swing.JLabel lblMemUso;
    private javax.swing.JLabel lblMemUtilizacao;
    private javax.swing.JLabel lblMemValorRAM;
    private javax.swing.JLabel lblMemValorUso;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JPanel pnlAplicativos1;
    private javax.swing.JPanel pnlProcessos;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JTable tbProcessos;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTabbedPane tbpGuias;
    // End of variables declaration//GEN-END:variables
}
